.\" Copyright (c) 2024 Omar Polo <op@omarpolo.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd August 2, 2024
.Dt AMUSED-MPRIS2 1
.Os
.Sh NAME
.Nm amused-mpris2
.Nd DBus control interface for amused
.Sh SYNOPSIS
.Nm
.Op Fl dv
.Op Fl s Ar socket
.Sh DESCRIPTION
.Nm
is a DBus interface to control the
.Xr amused 1
music player.
It exposes the
.Dq standard
MPRIS2
.Pq Media Player Remote Interfacing Specification
interface that DBus-capable program can use to query and control
.Xr amused 1 .
.Pp
The following options are available:
.Bl -tag -width tenletters
.It Fl d
Do not daemonize.
.Nm
will run in the foreground and log to standard error.
.It Fl s Ar socket
Path to the
.Xr amused 1
control socket.
By default
.Pa /tmp/amused-UID
is used.
.It Fl v
Produce more verbose output.
.El
.Sh ENVIRONMENT
.Bl -tag -width tenletters
.It Ev TEMPDIR
Path to the directory where the control socket looked for.
Defaults to
.Pa /tmp .
.El
.Sh SEE ALSO
.Xr amused 1
.Sh AUTHORS
.An -nosplit
The
.Nm
program was written by
.An Omar Polo Aq Mt op@omarpolo.com .
