.\" Copyright (c) 2023 Omar Polo <op@omarpolo.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd August 14, 2023
.Dt AMUSED-WEB 1
.Os
.Sh NAME
.Nm amused-web
.Nd web interface for the amused music player
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl s Ar socket
.Op Oo Ar host Oc Ar port
.Sh DESCRIPTION
.Nm
is a web interface to control the
.Xr amused 1
music player.
It exposes a web server that listen on
.Ar host
at the given
.Ar port .
By default all IPv4 and IPv6 address at port 9090.
.Pp
The following options are available:
.Bl -tag -width tenletters
.It Fl s Ar socket
Path to the
.Xr amused 1
control socket.
By default
.Pa /tmp/amused-UID
is used.
.It Fl v
Produce more verbose output.
.El
.Sh SEE ALSO
.Xr amused 1
.Sh AUTHORS
.An -nosplit
The
.Nm
program was written by
.An Omar Polo Aq Mt op@omarpolo.com .
.Sh BUGS
The web interface doesn't update itself automatically.
Periodically refresh are needed.
