.\" Copyright (c) 2023, 2024 Omar Polo <op@omarpolo.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd July 30, 2024
.Dt AMUSED-WEB 1
.Os
.Sh NAME
.Nm amused-web
.Nd web interface for the amused music player
.Sh SYNOPSIS
.Nm
.Op Fl dv
.Op Fl s Ar socket
.Op Oo Ar host Oc Ar port
.Sh DESCRIPTION
.Nm
is a web interface to control the
.Xr amused 1
music player.
It exposes a web server that listen on
.Ar host
at the given
.Ar port ,
by default localhost on port 9090.
If
.Ar host
is
.Sq * ,
which has to be escaped for the shell,
then it will listen on all IPv4 and IPv6 addresses.
.Pp
The following options are available:
.Bl -tag -width tenletters
.It Fl d
Do not daemonize.
.Nm
will run in the foreground and log to standard error.
.It Fl s Ar socket
Path to the
.Xr amused 1
control socket.
By default
.Pa /tmp/amused-UID
is used.
.It Fl v
Produce more verbose output.
.El
.Sh ENVIRONMENT
.Bl -tag -width tenletters
.It Ev TEMPDIR
Path to the directory where the control socket looked for.
Defaults to
.Pa /tmp .
.El
.Sh SEE ALSO
.Xr amused 1
.Sh AUTHORS
.An -nosplit
The
.Nm
program was written by
.An Omar Polo Aq Mt op@omarpolo.com .
.Sh CAVEATS
.Nm
should be hosted only in trusted networks because it doesn't employ all
the techniques that would be needed to prevent abuses in public
networks.
If reachable in a public network, it should at least be protected by a
password.
.Pp
Depending on the browser and the address from where
.Nm
is accessed, the use of TLS may be required.
